#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	use net
	after canna freewnn
}

start() {
	ebegin "Starting IIIMF input server"
	start-stop-daemon --start --background --quiet --exec /usr/bin/iiimd
	eend $?
}

stop() {
	ebegin "Stopping IIIMF input server"
	start-stop-daemon --stop --quiet --exec /usr/bin/iiimd
	eend $?
}
