#!/sbin/runscript
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

depend() {
	need net
}

start() {
	ebegin "Starting quickml"
	start-stop-daemon --start --quiet --exec /usr/sbin/quickml-ctl start 1> /dev/null
	eend $?
}

stop() {
	ebegin "Stopping quickml"
	start-stop-daemon --stop --quiet --pidfile /var/run/quickml.pid
	eend $?
}
