#!/sbin/runscript
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	use net
}

checkconfig() {
	if [ ! -e /etc/pglb.conf ] ; then
		eerror "You need to create /etc/pglb.conf first."
		eerror "An example can be found in /etc/pglb.conf.sample"
		return 1
	fi
}
start() {
	checkconfig || return 1
	ebegin "Starting load balance server"
	/usr/bin/pglb -D /etc
	eend $?
}

stop() {
	ebegin "Stopping load balance server"
	/usr/bin/pglb stop -D /etc
	eend $?
}
