#!/sbin/runscript
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /home/cvsroot/gentoo-x86/dev-db/postgresql/files/postgresql.init-7.3.4,v 1.3 2004/02/27 05:44:48 nakano Exp $

depend() {
	use net
}

checkconfig() {
	if [ ! -e /etc/pgreplicate.conf ] ; then
		eerror "You need to create /etc/pgreplicate.conf first."
		eerror "An example can be found in /etc/pgreplicate.conf.sample"
		return 1
	fi
}

start() {
	checkconfig || return 1
	ebegin "Starting replication server"
	/usr/bin/pgreplicate -D /etc
	eend $?
}

stop() {
	ebegin "Stopping replication server"
	/usr/bin/pgreplicate stop -D /etc
	eend $?
}
